regalias/regalias/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings

from users.views import home


urlpatterns = [
    path('media/(<path>)', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/(<path>)', serve, {'document_root': settings.STATIC_ROOT}),
    path('', home, name='index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('cliente/', include('clientes.urls')),
    path('materia/prima/', include('materiales.urls')),
    path('pedido/', include('pedidos.urls')),
    path('venta/', include('ventas.urls')),
    path('reporte/', include('reportes.urls')),
]

regalias/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('new/', views.user_creation, name='user-new'),
    path('update/', views.update_information, name='user-complete-information'),
    path('users/index', views.user_index, name='users-index'),
    path('change/pass/', views.reset_pass, name='user-reset-pass'),
    path('change/username/', views.change_username, name='user-change-username'),
    path('user/lista/', views.lista_usuarios, name='user-list'),
    path('user/<int:user_id>/baja/', views.baja_user, name='user-baja'),
    path('user/<int:user_id>/admin/activate/', views.activate_superuser, name='user-admin-activate'),
    path('user/<int:user_id>/admin/baja/', views.deactivate_superuser, name='user-admin-baja'),
    path('user/<int:user_id>/activate/', views.activate_user, name='user-activate'),
    path('<int:user_id>/permission/', views.permisos, name='user-permission'),
    path('add/<int:grupo_id>/<int:user_id>/permission/', views.add_grupo, name='user-add-permission'),
    path('remove/<int:grupo_id>/<int:user_id>/permission/', views.remove_grupo, name='user-remove-permission'),


    path('user/<int:user_id>/ventas', views.ventas_user, name='user-ventas'),
    path('user/<int:user_id>/pdf/<int:iyear>/<int:imonth>/<int:iday>/ventas/<int:fyear>/<int:fmonth>/<int:fday>', views.pdf_ventas_user, name='user-pdf-ventas-fechas'),

    path('mis/ventas', views.mis_ventas, name='mis-ventas'),
    path('mis/ventas/pdf/<int:iyear>/<int:imonth>/<int:iday>/ventas/<int:fyear>/<int:fmonth>/<int:fday>', views.pdf_misventas, name='user-pdf-mis_ventas-fechas'),

    path('empresa', views.info_empresa, name='empresa_info'),
    path('empresa/new', views.new_empresa, name='empresa_new'),
    path('empresa/update', views.update_empresa, name='empresa_update'),

    path('color', views.index_colores, name='color-index'),
    path('color/new', views.new_color, name='color-new'),
    path('color/<int:color_id>/update', views.update_color, name='color-update'),
    path('color/new/popup', views.new_color_popup, name='color-new-popup'),

    path('color/name/ajax', views.color_ajax, name='color-ajax'),

]

regalias/materiales/models.py
from django.db import models
from django.contrib.auth.models import User

from clientes.models import Ciudad
from users.models import Color

class Proveedor(models.Model):
    nit = models.IntegerField(verbose_name='NIT', null=True)
    proveedor = models.CharField(max_length=100, verbose_name='Nombre Proveedor')
    telefono = models.CharField(max_length=10)
    direccion = models.CharField(max_length=100)
    email = models.EmailField(null=True)
    estado = models.BooleanField(default=True)
    origen = models.ForeignKey(Ciudad, null=True, on_delete=models.PROTECT, verbose_name='Ciudad de origen')
    def __unicode__(self):
        return '%s' %self.proveedor
    def __str__(self):
        return '%s' % self.proveedor
    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'
        ordering = ['proveedor']

CHOICEUNIDAD = (
    ('Kilos', 'Kilos'),
)

COLORCHOICE = (
    ('Azul', 'Azul'),
    ('Rojo', 'Rojo'),
    ('Naranja', 'Naranja'),
    ('Verde', 'Verde'),
)

TIPOCHOICES = (
    ('Calamina', 'Calamina'),
    ('Clavos', 'Clavos'),
)

UNIDADCHOICES = (
    ('Bobina', 'Bobina'),
    ('Alambron', 'Alambron'),
)

class CodigoMateriaPrima(models.Model):
    codigo = models.CharField(max_length=50, verbose_name='Codigo Materia Prima', unique=True)
    def __unicode__(self):
        return '%s' % self.codigo

    def __str__(self):
        return '%s' % self.codigo

class MateriaPrima(models.Model):
    tipo = models.CharField(max_length=10, verbose_name='Tipo Material', default='Calamina', choices=TIPOCHOICES)
    codigo = models.ForeignKey(CodigoMateriaPrima, models.PROTECT, null=True)
    nro_serie = models.CharField(max_length=100, verbose_name='Numero de Serie', null=True)
    marca = models.CharField(max_length=100, verbose_name='Marca Producto')
    cantidad = models.IntegerField(verbose_name='Cantidad', default='1')
    unidad = models.CharField(max_length=50, verbose_name='Unidad', default='Bobina', null=True, choices=UNIDADCHOICES)
    espesor = models.FloatField(verbose_name='Espesor', help_text='En Milimetros (mm)')
    ancho = models.FloatField(verbose_name='Ancho', help_text='En Metros Lineales (ml)', null=True, blank=True, default=0)
    medida = models.CharField(max_length=100, choices=CHOICEUNIDAD, verbose_name='Tipo de Medida', null=True)
    peso = models.IntegerField(verbose_name='Peso')
    longitud = models.IntegerField(verbose_name='Longitud Aproximada', help_text='En Metros Lineales', null=True, blank=True, default=0)
    color = models.CharField(max_length=100, verbose_name='Color', default='Sin Color', null=True, blank=True)
    fecha = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    estado = models.BooleanField(default=True)
    salida = models.FloatField(default=0)
    precioc = models.FloatField(default=0, verbose_name='Precio de Compra', help_text='En Bolivianos')
    stock = models.FloatField(default=0)
    proveedor = models.ForeignKey(Proveedor, null=True, on_delete=models.PROTECT)
    
    def __unicode__(self):
        return '%s: %s de   %smm de espesor * %sml de ancho' % (
            self.unidad, self.color, self.espesor, self.ancho)
    def __str__(self):
        return '%s: %s de   %smm de espesor * %sml de ancho' % (
            self.unidad, self.color, self.espesor, self.ancho)
    def detalle(self):
        return '%s: %s de   %smm de espesor * %sml de ancho' % (
        self.unidad, self.color, self.espesor, self.ancho)
    class Meta:
        verbose_name = 'Materia Prima Calamina'
        verbose_name_plural = 'Materia Prima Calaminas'
        ordering = ['fecha']

class Precio(models.Model):
    codigo = models.CharField(max_length=10, verbose_name='Codigo', help_text='Codigo de tipo de Calamina')
    materia = models.ForeignKey(MateriaPrima, null=True, on_delete=models.PROTECT, help_text='Materia Prima')
    descripcion = models.CharField(max_length=200, verbose_name='Descripcion', help_text='Pequeña descripción')
    precio = models.FloatField(verbose_name='Precio Metro L.', help_text='En Bolivianos')
    espesor = models.FloatField(verbose_name='Espesor', help_text='En Milimetros (mm)', null=True)
    color = models.CharField(max_length=100, verbose_name='Color', default='Sin Color', null=True)
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s: %s' % (self.codigo, self.descripcion)
    def __str__(self):
        return '%s: %s' % (self.codigo, self.descripcion)
    class Meta:
        verbose_name = 'Tabla de Precio'
        verbose_name_plural = 'Tabla de Precios'
        ordering = ['precio']


TIPESCLAVOS = (
    ('Unidad', 'Unidad'),
    ('Caja', 'Caja'),
)

class CodigoClavo(models.Model):
    codigo = models.CharField(max_length=50, verbose_name='Codigo De Clavo', unique=True)

    def __unicode__(self):
        return '%s' % self.codigo

    def __str__(self):
        return '%s' % self.codigo

class PrecioClavos(models.Model):
    codigo = models.ForeignKey(CodigoClavo, on_delete=models.Model)
    tipo = models.CharField(max_length=20, null=True, choices=TIPESCLAVOS)
    descripcion = models.CharField(max_length=200, verbose_name='Descripcion')
    precio = models.FloatField(verbose_name='Precio Kilo.', help_text='En Bolivianos')
    longitud = models.FloatField(verbose_name='Longitud', help_text='En Milimetros (mm)', null=True)
    stock = models.IntegerField(default=1, help_text='En Kilos')
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s: %s'%(self.codigo, self.descripcion)
    def __str__(self):
        return '%s: %s' % (self.codigo, self.descripcion)
    class Meta:
        verbose_name = 'Tabla de Precio Clavo'
        verbose_name_plural = 'Tabla de Precios Clavos'
        ordering = ['precio']



class DetallePrecioClavo(models.Model):
    fecha = models.DateField(auto_now_add=True)
    cantidad = models.IntegerField()
    precioclavo = models.ForeignKey(PrecioClavos, on_delete=models.Model) 
    def __unicode__(self):
        return '%s'% self.precioclavo
    def __str__(self):
        return '%s' % self.precioclavo


class TipoCalamina(models.Model):
    tipo = models.CharField(max_length=50, verbose_name='Tipo De Calamina', unique=True)
    def __unicode__(self):
        return  '%s' % self.tipo
    def __str__(self):
        return '%s' % self.tipo

class CodigoCalamina(models.Model):
    codigo = models.CharField(max_length=50, verbose_name='Codigo De Calamina', unique=True)

    def __unicode__(self):
        return '%s' % self.codigo

    def __str__(self):
        return '%s' % self.codigo

class PrecioCalamina(models.Model):
    tipo = models.ForeignKey(TipoCalamina, on_delete=models.PROTECT)
    codigo = models.ForeignKey(CodigoCalamina, on_delete=models.PROTECT)
    color = models.ForeignKey(Color, on_delete=models.PROTECT)
    nro_codigo = models.CharField(max_length=50, null=True)
    precio = models.FloatField(verbose_name='Precio Metro L.', help_text='En Bolivianos')
    espesor = models.FloatField(verbose_name='Espesor', help_text='En Milimetros (mm)', null=True)
    ancho = models.FloatField(verbose_name='Ancho', help_text='En Metros Lineales (ml)')
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s - %s - %s Bs.' % (self.codigo, self.tipo, self.precio)
    def __str__(self):
        return '%s - %s - %s Bs.' % (self.codigo, self.tipo, self.precio)
    class Meta:
        verbose_name = 'Precio de Calamina'
        verbose_name_plural = 'Precios de Calamina'
        ordering = ['tipo', 'color', 'codigo']

regalias/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

class Empresa(models.Model):
    nit = models.CharField(max_length=300, verbose_name='NIT Empresa')
    nro = models.CharField(max_length=300, verbose_name='Numero de Autorizacion')
    key = models.CharField(max_length=500, verbose_name='Llave de Dosificacion')
    vencimiento = models.DateField(null=True)
    sms = models.TextField(max_length=500, null=True, verbose_name='Mensaje de Factura')
    def __unicode__(self):
        return '%s'%self.nit
    def __str__(self):
        return '%s' % self.nit

class Color(models.Model):
    color = models.CharField(max_length=100, verbose_name='Descripcion de Color', unique=True)
    codigo = models.CharField(max_length=100, null=True)
    def __unicode__(self):
        return '%s'%self.color
    def __str__(self):
        return '%s' % self.color
    class Meta:
        verbose_name = 'Color'
        verbose_name_plural = 'Colores'
        ordering = ['color']

class ColorName(models.Model):
    nombre_c = models.CharField(max_length=50)
    hexa = models.CharField(max_length=20)

SEX = (
    ('Masculino', 'Masculino'),
    ('Femenino', 'Femenino'),
)
class Perfil(models.Model):
    direccion = models.CharField(max_length=100, verbose_name='Direccion', null=True)
    celular = models.IntegerField(verbose_name='Celular', null=True)
    sexo = models.CharField(max_length=50, choices=SEX, null=True)
    #avatar = models.ImageField(upload_to='avatar', verbose_name='Seleccione foto perfil')
    usuarios = models.OneToOneField(User, unique=True, on_delete=models.PROTECT, null=True)
    def __unicode__(self):
        return '%s'%(self.usuarios)
    def __str__(self):
        return '%s' % (self.usuarios)
    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

regalias/regalias/templates/clavos/add_stock.html
{% extends '__form.html' %}

{% block title %}
Registrar Stock
{% endblock %}
{% block legend %}
Registrar Stock
{% endblock %}

regalias/regalias/templates/clavos/index_inventario.html
{% extends 'base.html' %}

{% block title %}
Nuestro Inventario
{% endblock %}

{% block content %}
{% load helper_material %}
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2 class="app">Inventario Clavos</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a href="{% url 'pdf-inventario-clavo' %}" class="btn btn-danger " target="_blank" data-toggle="tooltip" title="Psar a PDF!">
            <strong style="color:black;">PDF <i class="fa fa-file-pdf-o"></i></strong>
        </a></li>
        <!--li><a href="" type="button" href="" class="btn btn-success" data-toggle="tooltip" title="Nuevo Cliente!"><span class="glyphicon glyphicon-plus" ></span></a></li-->
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li><a class="close-link" href=""><i class="fa fa-close"></i></a>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<div class="x_content">
  <p class="text-muted font-13 m-b-30">
    Este es una tabla donde contiene los datos de clavos registrados.
</p>
<table class="table striped hovered border bordered" width="100%">
    <thead>
        <tr>
            <th>#</th>
            <th>CODIGO</th>
            <th>TIPO</th>
            <th>DETALLE</th>
            <th>LONGITUD(mm)</th>
            <th>PRECIO</th>
            <th>STOCK</th>
            <th>SALIDA</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for inventario in inventarios %}
        <tr>
            <td>{{ forloop.counter |upper}}</td>
            <td>{{ inventario.codigo |upper}}</td>
            <td>{{ inventario.tipo|upper}}</td>
            <td>{{ inventario.descripcion |upper}}</td>
            <td>{{ inventario.longitud |upper}}</td>
            <td> <span class="badge" style="background-color:#3a87ad">{{ inventario.precio |upper}} Bs.</span></td>
            <td><span class="badge" style="background-color:#468847">{{ inventario.stock |upper}} U. </span></td>
            <td>{% salidamaterial inventario %}</td>
            <td>
                    <!--a href="{% url 'precio-update-clavo' inventario.id %}" class="btn btn-warning btn-xs" title="Editar Material">
                        <i class="fa fa-pencil-square"></i>
                    </a>
                    <a href="{% url 'precio-baja-clavo' inventario.id %}" class="btn btn-danger btn-xs" title="Baja Precio">
                        <i class="fa fa-times-circle"></i>
                    </a-->
                    {% if user.is_superuser %}
                    <a href="{% url 'precio-stock-clavo' inventario.id %}" class="btn btn-success btn-xs" title="Aumentar Stock">
                        <i class="fa fa-edit"></i>
                    </a>

                    
                </a>
                <button type="button" class="btn btn-primary btn-xs openmodal" data-toggle="modal" data-target=".bs-example-modal-lg{{ inventario.id }}" title="Detalle Entrada">
                    <i class="fa fa-list-alt"></i>
                </button>
                
                
                {% endif %}
                
                
                <div class="modal fade bs-example-modal-lg{{ inventario.id }}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                    <div class="modal-dialog modal-md" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title app" >Detalle de Entradas</h4>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <p> Codigo: {{inventario.codigo}}</p>
                                        <p> Descripcion: {{inventario.descripcion}}</p>
                                        <p>Stock Actual: {{inventario.stock}}</p>
                                        <table class="table bordered col-md-12" style="width: 100%">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Fecha</th>
                                                    <th>Cantidad</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for d in inventario.detalleprecioclavo_set.select_related.all %} 
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>{{ d.fecha }}</td>
                                                    <td>{{ d.cantidad }}</td>
                                                    <td>{{ d.precioclavo }}</td>
                                                    <td>
                                                    </td>
                                                </tr>
                                                {% endfor %}

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <br><br><br><br><br>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
</div>
{% endblock %}
{% block js %}
<script>
$(document).ready(function () {
    $('.btn.btn-primary.btn-xs.openmodal').click(function () {
            /*$('#DataTables_Table_1_filter').addClass('hide');
            $('#DataTables_Table_1_info').addClass('hide');
            $('#DataTables_Table_1_paginate').addClass('hide');*/
        })
});

</script>
{% endblock %}

regalias/regalias/templates/clavos/index_precio.html
{% extends 'base.html' %}

{% block title %}
Nuestros Precios
{% endblock %}

{% block content %}
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2 class="app">Precios Clavos  <small style="font-family:arial">Lista de Clavos</small></h2>
      <ul class="nav navbar-right panel_toolbox">
        <!--li><a href="" class="btn btn-danger " target="_blank" data-toggle="tooltip" title="Psar a PDF!">
            <strong style="color:black;"><i class="fa fa-file-pdf-o"></i></strong>
        </a></li-->
        <li><a href="{% url 'precio-new-clavo' %}" type="button" href="" class="btn btn-success" data-toggle="tooltip" title="Nuevo Precio!" id="register_precio">
          <strong style="color:black">AGREGAR <span style="color:black;" class="glyphicon glyphicon-plus" ></span> </strong></a>
      </li>
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link" href=""><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <p class="text-muted font-13 m-b-30">
        Este es una tabla donde contiene los datos de los precios de clavos registrados.
    </p>
    <table class="table striped hovered border bordered" width="100%">
        <thead>
            <tr>
                <th>#</th>
                <th>CODIGO</th>
                <th>DESCRIPCCIÓN</th>                
                <th>LONGITUD (mm)</th>                
                <th>PRECIO (Bs.)</th>
                <th>STOCK </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for precio in precios %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ precio.codigo |upper}}</td>
                <td>{{ precio.descripcion |upper}}</td>
                <td>{{ precio.longitud |upper}}</td>
                <td><span class="badge" style="background-color:#3a87ad">{{ precio.precio |upper}} Bs. </span></td>
                    <td><span class="badge" style="background-color:#26b99a">{{ precio.stock |upper}} : {{precio.tipo}}</span></td>               
                <td>
                    <a href="{% url 'precio-update-clavo' precio.id %}" class="btn btn-warning btn-xs" title="Editar Precio">
                        <i class="fa fa-pencil-square"></i>
                    </a>
                    <a href="{% url 'precio-baja-clavo' precio.id %}" class="btn btn-danger btn-xs" title="Baja Precio">
                        <i class="fa fa-times-circle"></i>
                    </a>
                    <!--a href="{% url 'precio-stock-clavo' precio.id %}" class="btn btn-success btn-xs" title="Aumentar Stock">
                        <i class="fa fa-edit"></i>
                    </a>
                    <button type="button" class="btn btn-primary btn-xs openmodal" data-toggle="modal" data-target=".bs-example-modal-lg{{ precio.id }}" title="Detalle Entrada">
                        <i class="fa fa-list-alt"></i>
                    </button-->
                    <div class="modal fade bs-example-modal-lg{{ precio.id }}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                        <div class="modal-dialog modal-md" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Detalle de Entradas</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <table class="table bordered col-md-12" style="width: 100%">
                                                <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Fecha</th>
                                                        <th>Cantidad</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for d in precio.detalleprecioclavo_set.select_related.all %}
                                                        <tr>
                                                            <td>{{ forloop.counter }}</td>
                                                            <td>{{ d.fecha }}</td>
                                                            <td>{{ d.cantidad }}</td>
                                                            <td></td>
                                                        </tr>
                                                    {% endfor %}

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <br><br><br><br><br>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>
{% endblock %}
{% block js %}
    <script>
    $(document).ready(function () {
        $('.btn.btn-primary.btn-xs.openmodal').click(function () {
            /*$('#DataTables_Table_1_filter').addClass('hide');
            $('#DataTables_Table_1_info').addClass('hide');
            $('#DataTables_Table_1_paginate').addClass('hide');*/
        })
    });

    </script>
{% endblock %}

regalias/regalias/templates/clavos/new_codigoclavo_popup.html
{% extends '__form_popup.html' %}

{% block title %}
Registrar Codigo Clavo
{% endblock %}

{% block legend %}
Registrar Codigo Clavo
{% endblock %}

regalias/regalias/templates/clavos/new_precio.html
{% extends '__form.html' %}

{% block title %}
Registrar Precio
{% endblock %}

{% block legend %}
Registrar Precio Clavo
{% endblock %}

{% block cuerpo-form %}
{% for field in form %}
<div class="form-group">
    {% if field.errors %}
        <div class="mypadding2 bg-red fg-white margin10 no-margin-right no-margin-left">
            <i class="fa fa-exclamation-triangle"></i>{{ field.errors }}
        </div>
    {% endif %}
    {{ field.label_tag }}
    {% if field.html_name == 'precio' %}
        <div class="col-sm-9 col-md-9 col-lg-9">
            {{ field }}
            {% if field.help_text %}
            <small class="fg-green block padding10 no-padding-top">
                <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
            </small>
            {% endif %}
        </div>
    {% elif field.html_name == 'codigo' %}
        <div class="col-sm-8 col-md-8 col-lg-8">
            {{ field }}
            {% if field.help_text %}
            <small class="fg-green block padding10 no-padding-top">
                <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
            </small>
            {% endif %}
        </div>
        <div class="col-sm-1" style="line-height: 30px">
            <a href="{% url 'precio-codigo-clavo-popup' %}" class="btn btn-success add-another" title="Registrar Ciudad" id="{{ field.auto_id }}">
                <i class="fa fa-plus-circle "></i>
            </a>
        </div>
    {% else %}
        <div class="col-sm-9 col-md-9 col-lg-9">
            {{ field }}
            {% if field.help_text %}
            <small class="fg-green block padding10 no-padding-top">
                <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
            </small>
            {% endif %}
        </div>
    {% endif %}
</div>
{% endfor %}
{% endblock %}

{% block js %}
    {% include '__popup_script.html' %}
    <script>
$(document).ready(function () {
    var html = '<option>------</option>';
    {% for color in coloresss %}
    html += '<option value="{{ color.color }}" id="{{ color.codigo }}">{{ color.color }}</option>';
    {% endfor %}
    //hiden();
    $('#id_color').change(function () {
        var color = $(this).val();
        $.ajax({
            data:{'id': color},
            url:"{% url 'material-ajax-color-colored' %}",
            type:'GET',
            success: function(data){
                $('#informarioncolor').css('background-color', data[0].codigo)
            },
            failure: function(data){
                console.log('error')
            }
        });
    })
});
</script>
{% endblock %}

regalias/regalias/templates/clavos/pdf_inventario_clavo.html
{% extends 'report.html' %}

{% block title %}
Detalle de Entradas
{% endblock %}

{% block cuerpo %}
{% load helper_material %}

<style>

.app th{
    background-color: #d7d7d7;
    border :1px solid white;
    font-family: courier;
}
.app td{
    text-align:center;
    border-bottom: 1px solid #d7d7d7;
    
}
</style>
<h2 align="center">DETALLE DE ENTRADAS</h2>
{% for inventario in inventarios %}
<table >
    <tr>
        <th class="celdas" colspan="4" width="100%" align="left" style="font-family: courier; font-size:15px; border: white;background-color:#d7d7d7;"> I. DATOS IDENTIFICACIÓN DE CLAVO: {{inventario.codigo|upper}}<strong></strong> </th>
    </tr>
    <tr></tr>
    <tr  style="font-family: courier; font-size:12px;">
        <td width="17%">
            <strong> CODIGO: </strong></br>
            <strong> TIPO. </strong></br>
            <strong> DESCRIPCIÓN: </strong></br>
            <strong> LONGITUD: </strong></br>

        </td>
        <td width="35%">

        {{ inventario.codigo |upper }}</br>
    {{ inventario.tipo |upper }}</br>
{{ inventario.descripcion |upper }}</br>
{{ inventario.longitud |upper}} m.m.</br>


</td>
<td width="17%">
    <strong> PRECIO: </strong></br>
    <strong> STOCK: </strong></br>
    <strong> SALIDA: </strong></br>
</td>
<td width="35%">

   <span class="badge" style="color:#3a87ad">{{ inventario.precio |upper }} Bs.</span></br>
   <span class="badge" style="color:#468847">{{ inventario.stock |upper }} U. </span></br>
{% salidamaterial inventario %}</br>

</td>
</tr>
<br>

<table style="font-size:11px; padding-top:3px;">
    <th class="celdas" colspan="3" width="100%" align="left" style="font-family: courier; font-size:15px; border: white;"> II. DETALLE DE ENTRADA <strong></strong> </th>
    <thead>
        <tr class="app">
            <th >#</th>
            <th>Fecha</th>
            <th>Cantidad</th>
        </tr>
    </thead>
    <tbody>
        {% for d in inventario.detalleprecioclavo_set.select_related.all %} 
        <tr class="app">
            <td>{{ forloop.counter }}</td>
            <td>{{ d.fecha | upper}}</td>
            <td>{{ d.cantidad }}</td>
        </tr>
        {% endfor %}

    </tbody>
</table>
{% endfor %}

{% endblock %} 

regalias/regalias/templates/clavos/update_precio.html
{% extends '__form.html' %}

{% block title %}
Modificar Precio
{% endblock %}

{% block legend %}
Modificar Precio
{% endblock %}

{% block submit %}
Modificar
{% endblock %}

{% block jsss %}
<script>
$(document).ready(function () {
    var html = '<option>------</option>';
    {% for color in colores %}
        html += '<option value="{{ color.color }}">{{ color.color }}</option>';
    {% endfor %}
    $('#id_color').html(html);
});
</script>
{% endblock %}