regalias/regalias/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings

from users.views import home


urlpatterns = [
    path('media/(<path>)', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/(<path>)', serve, {'document_root': settings.STATIC_ROOT}),
    path('', home, name='index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('cliente/', include('clientes.urls')),
    path('materia/prima/', include('materiales.urls')),
    path('pedido/', include('pedidos.urls')),
    path('venta/', include('ventas.urls')),
    path('reporte/', include('reportes.urls')),
]

regalias/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('new/', views.user_creation, name='user-new'),
    path('update/', views.update_information, name='user-complete-information'),
    path('users/index', views.user_index, name='users-index'),
    path('change/pass/', views.reset_pass, name='user-reset-pass'),
    path('change/username/', views.change_username, name='user-change-username'),
    path('user/lista/', views.lista_usuarios, name='user-list'),
    path('user/<int:user_id>/baja/', views.baja_user, name='user-baja'),
    path('user/<int:user_id>/admin/activate/', views.activate_superuser, name='user-admin-activate'),
    path('user/<int:user_id>/admin/baja/', views.deactivate_superuser, name='user-admin-baja'),
    path('user/<int:user_id>/activate/', views.activate_user, name='user-activate'),
    path('<int:user_id>/permission/', views.permisos, name='user-permission'),
    path('add/<int:grupo_id>/<int:user_id>/permission/', views.add_grupo, name='user-add-permission'),
    path('remove/<int:grupo_id>/<int:user_id>/permission/', views.remove_grupo, name='user-remove-permission'),


    path('user/<int:user_id>/ventas', views.ventas_user, name='user-ventas'),
    path('user/<int:user_id>/pdf/<int:iyear>/<int:imonth>/<int:iday>/ventas/<int:fyear>/<int:fmonth>/<int:fday>', views.pdf_ventas_user, name='user-pdf-ventas-fechas'),

    path('mis/ventas', views.mis_ventas, name='mis-ventas'),
    path('mis/ventas/pdf/<int:iyear>/<int:imonth>/<int:iday>/ventas/<int:fyear>/<int:fmonth>/<int:fday>', views.pdf_misventas, name='user-pdf-mis_ventas-fechas'),

    path('empresa', views.info_empresa, name='empresa_info'),
    path('empresa/new', views.new_empresa, name='empresa_new'),
    path('empresa/update', views.update_empresa, name='empresa_update'),

    path('color', views.index_colores, name='color-index'),
    path('color/new', views.new_color, name='color-new'),
    path('color/<int:color_id>/update', views.update_color, name='color-update'),
    path('color/new/popup', views.new_color_popup, name='color-new-popup'),

    path('color/name/ajax', views.color_ajax, name='color-ajax'),

]

regalias/clientes/models.py
from __future__ import unicode_literals
from django.db import models

from django.core.exceptions import ValidationError

def validate_ci(value):
    if len(str(value)) != 10 and len(str(value)) != 8 and len(str(value)) != 7:
        raise ValidationError(u'%s No es un Cedula de Identidad'% value)
    return validate_ci

GENERO = (
    ('Masculino','Masculino'),
    ('Femenino', 'Femenino'),
)

class Pais(models.Model):
    pais = models.CharField(max_length=30, verbose_name='Nombre', unique=True)
    def __str__(self):
        return self.pais
    def __unicode__(self):
        return self.pais
    class Meta:
        ordering = ['pais']
        verbose_name = 'País'
        verbose_name_plural = 'Paices'

class Ciudad(models.Model):
    ciudad = models.CharField(max_length=30, verbose_name='Nombre', unique=True)
    pais = models.ForeignKey(Pais, on_delete=models.PROTECT)
    def __str__(self):
        return self.ciudad
    def __unicode__(self):
        return self.ciudad
    class Meta:
        ordering = ['pais', 'ciudad']
        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'


class Cliente(models.Model):
    nit = models.CharField(max_length=20, verbose_name='NIT/CI', null=True, unique=True)
    razon = models.CharField(max_length=100, verbose_name='Nombre o Razon Social', null=True)
    direccion = models.CharField(max_length=50, verbose_name='Direccion')
    telefono = models.CharField(max_length=15, verbose_name='Telefono/Ceular')
    email = models.EmailField(blank=True, verbose_name='Correo Electronico')
    ciudad = models.ForeignKey(Ciudad, verbose_name='Ciudad', on_delete=models.PROTECT)
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s %s' % (self.nit, self.razon)
    def __str__(self):
        return '%s %s' % (self.nit, self.razon)

regalias/materiales/models.py
from django.db import models
from django.contrib.auth.models import User

from clientes.models import Ciudad
from users.models import Color

class Proveedor(models.Model):
    nit = models.IntegerField(verbose_name='NIT', null=True)
    proveedor = models.CharField(max_length=100, verbose_name='Nombre Proveedor')
    telefono = models.CharField(max_length=10)
    direccion = models.CharField(max_length=100)
    email = models.EmailField(null=True)
    estado = models.BooleanField(default=True)
    origen = models.ForeignKey(Ciudad, null=True, on_delete=models.PROTECT, verbose_name='Ciudad de origen')
    def __unicode__(self):
        return '%s' %self.proveedor
    def __str__(self):
        return '%s' % self.proveedor
    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'
        ordering = ['proveedor']

CHOICEUNIDAD = (
    ('Kilos', 'Kilos'),
)

COLORCHOICE = (
    ('Azul', 'Azul'),
    ('Rojo', 'Rojo'),
    ('Naranja', 'Naranja'),
    ('Verde', 'Verde'),
)

TIPOCHOICES = (
    ('Calamina', 'Calamina'),
    ('Clavos', 'Clavos'),
)

UNIDADCHOICES = (
    ('Bobina', 'Bobina'),
    ('Alambron', 'Alambron'),
)

class CodigoMateriaPrima(models.Model):
    codigo = models.CharField(max_length=50, verbose_name='Codigo Materia Prima', unique=True)
    def __unicode__(self):
        return '%s' % self.codigo

    def __str__(self):
        return '%s' % self.codigo

class MateriaPrima(models.Model):
    tipo = models.CharField(max_length=10, verbose_name='Tipo Material', default='Calamina', choices=TIPOCHOICES)
    codigo = models.ForeignKey(CodigoMateriaPrima, models.PROTECT, null=True)
    nro_serie = models.CharField(max_length=100, verbose_name='Numero de Serie', null=True)
    marca = models.CharField(max_length=100, verbose_name='Marca Producto')
    cantidad = models.IntegerField(verbose_name='Cantidad', default='1')
    unidad = models.CharField(max_length=50, verbose_name='Unidad', default='Bobina', null=True, choices=UNIDADCHOICES)
    espesor = models.FloatField(verbose_name='Espesor', help_text='En Milimetros (mm)')
    ancho = models.FloatField(verbose_name='Ancho', help_text='En Metros Lineales (ml)', null=True, blank=True, default=0)
    medida = models.CharField(max_length=100, choices=CHOICEUNIDAD, verbose_name='Tipo de Medida', null=True)
    peso = models.IntegerField(verbose_name='Peso')
    longitud = models.IntegerField(verbose_name='Longitud Aproximada', help_text='En Metros Lineales', null=True, blank=True, default=0)
    color = models.CharField(max_length=100, verbose_name='Color', default='Sin Color', null=True, blank=True)
    fecha = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    estado = models.BooleanField(default=True)
    salida = models.FloatField(default=0)
    precioc = models.FloatField(default=0, verbose_name='Precio de Compra', help_text='En Bolivianos')
    stock = models.FloatField(default=0)
    proveedor = models.ForeignKey(Proveedor, null=True, on_delete=models.PROTECT)
    
    def __unicode__(self):
        return '%s: %s de   %smm de espesor * %sml de ancho' % (
            self.unidad, self.color, self.espesor, self.ancho)
    def __str__(self):
        return '%s: %s de   %smm de espesor * %sml de ancho' % (
            self.unidad, self.color, self.espesor, self.ancho)
    def detalle(self):
        return '%s: %s de   %smm de espesor * %sml de ancho' % (
        self.unidad, self.color, self.espesor, self.ancho)
    class Meta:
        verbose_name = 'Materia Prima Calamina'
        verbose_name_plural = 'Materia Prima Calaminas'
        ordering = ['fecha']

class Precio(models.Model):
    codigo = models.CharField(max_length=10, verbose_name='Codigo', help_text='Codigo de tipo de Calamina')
    materia = models.ForeignKey(MateriaPrima, null=True, on_delete=models.PROTECT, help_text='Materia Prima')
    descripcion = models.CharField(max_length=200, verbose_name='Descripcion', help_text='Pequeña descripción')
    precio = models.FloatField(verbose_name='Precio Metro L.', help_text='En Bolivianos')
    espesor = models.FloatField(verbose_name='Espesor', help_text='En Milimetros (mm)', null=True)
    color = models.CharField(max_length=100, verbose_name='Color', default='Sin Color', null=True)
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s: %s' % (self.codigo, self.descripcion)
    def __str__(self):
        return '%s: %s' % (self.codigo, self.descripcion)
    class Meta:
        verbose_name = 'Tabla de Precio'
        verbose_name_plural = 'Tabla de Precios'
        ordering = ['precio']


TIPESCLAVOS = (
    ('Unidad', 'Unidad'),
    ('Caja', 'Caja'),
)

class CodigoClavo(models.Model):
    codigo = models.CharField(max_length=50, verbose_name='Codigo De Clavo', unique=True)

    def __unicode__(self):
        return '%s' % self.codigo

    def __str__(self):
        return '%s' % self.codigo

class PrecioClavos(models.Model):
    codigo = models.ForeignKey(CodigoClavo, on_delete=models.Model)
    tipo = models.CharField(max_length=20, null=True, choices=TIPESCLAVOS)
    descripcion = models.CharField(max_length=200, verbose_name='Descripcion')
    precio = models.FloatField(verbose_name='Precio Kilo.', help_text='En Bolivianos')
    longitud = models.FloatField(verbose_name='Longitud', help_text='En Milimetros (mm)', null=True)
    stock = models.IntegerField(default=1, help_text='En Kilos')
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s: %s'%(self.codigo, self.descripcion)
    def __str__(self):
        return '%s: %s' % (self.codigo, self.descripcion)
    class Meta:
        verbose_name = 'Tabla de Precio Clavo'
        verbose_name_plural = 'Tabla de Precios Clavos'
        ordering = ['precio']



class DetallePrecioClavo(models.Model):
    fecha = models.DateField(auto_now_add=True)
    cantidad = models.IntegerField()
    precioclavo = models.ForeignKey(PrecioClavos, on_delete=models.Model) 
    def __unicode__(self):
        return '%s'% self.precioclavo
    def __str__(self):
        return '%s' % self.precioclavo


class TipoCalamina(models.Model):
    tipo = models.CharField(max_length=50, verbose_name='Tipo De Calamina', unique=True)
    def __unicode__(self):
        return  '%s' % self.tipo
    def __str__(self):
        return '%s' % self.tipo

class CodigoCalamina(models.Model):
    codigo = models.CharField(max_length=50, verbose_name='Codigo De Calamina', unique=True)

    def __unicode__(self):
        return '%s' % self.codigo

    def __str__(self):
        return '%s' % self.codigo

class PrecioCalamina(models.Model):
    tipo = models.ForeignKey(TipoCalamina, on_delete=models.PROTECT)
    codigo = models.ForeignKey(CodigoCalamina, on_delete=models.PROTECT)
    color = models.ForeignKey(Color, on_delete=models.PROTECT)
    nro_codigo = models.CharField(max_length=50, null=True)
    precio = models.FloatField(verbose_name='Precio Metro L.', help_text='En Bolivianos')
    espesor = models.FloatField(verbose_name='Espesor', help_text='En Milimetros (mm)', null=True)
    ancho = models.FloatField(verbose_name='Ancho', help_text='En Metros Lineales (ml)')
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s - %s - %s Bs.' % (self.codigo, self.tipo, self.precio)
    def __str__(self):
        return '%s - %s - %s Bs.' % (self.codigo, self.tipo, self.precio)
    class Meta:
        verbose_name = 'Precio de Calamina'
        verbose_name_plural = 'Precios de Calamina'
        ordering = ['tipo', 'color', 'codigo']

regalias/regalias/templates/proveedores/baja_proveedores.html
{% extends 'base.html' %}

{% block title %}
Nuestros Proveedores
{% endblock %}

{% block content %}
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2 class="app">Proveedores Bajas <small style="font-family:arial">Lista de Proveedores</small></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li><a class="close-link" href=""><i class="fa fa-close"></i></a>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<div class="x_content">
  <p class="text-muted font-13 m-b-30">
    Este es una tabla donde contiene los datos de los proveedores registrados dados de baja.
</p>
<table class="table striped hovered border bordered" width="100%">
    <thead>
        <tr>
            <th width="30px">#</th>
            <th>NOMBRES</th>
            <th>ORIGEN</th>
            <th>TELÉFONO</th>
            <th>DIRECCIÓN</th>
            <th>EMAIL</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for proveedor in proveedores %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ proveedor.proveedor |upper}}</td>
            <td>{{ proveedor.origen.pais |upper}} / {{ proveedor.origen |upper}}</td>
            <td>{{ proveedor.telefono |upper}}</td>
            <td>{{ proveedor.direccion |upper}}</td>
            <td>{{ proveedor.email }}</td>
            <td>
                <a href="{% url 'proveedor-activate' proveedor.id %}" class="btn btn-success btn-xs" title="Editar Proveedor">
                    <i class="fa fa-check-square"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
</div>

{% endblock %}

regalias/regalias/templates/proveedores/detail.html
{% extends 'base.html' %}

{% block title %}
Detalle Cliente
{% endblock %}

{% block content %}
<div class="row">
    <h1>Detalle Proveedor</h1>
    <div class="col-md-6">
        <p class="lead">
            <strong>Proveedor: </strong>{{ proveedor.proveedor }}
        </p>
        <p class="lead">
            <strong>Telefono: </strong>{{ proveedor.telefono }}
        </p>
    </div>
    <div class="col-md-6">
        <p class="lead">
            <strong>Email: </strong>{{ proveedor.email }}
        </p>
        <p class="lead">
            <strong>Direccion: </strong>{{ proveedor.direccion }}
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <a href="{% url 'proveedor-baja' proveedor.id %}" class="btn btn-danger">
            <span class="fa fa-times-circle"></span> Baja Proveedor
        </a>
    </div>
</div>
{% endblock %}

regalias/regalias/templates/proveedores/new.html
{% extends '__form.html' %}

{% block title %}
Registrar Proveedor
{% endblock %}

{% block legend %}
Registrar Proveedor
{% endblock %}

{% block cuerpo-form %}
{% for field in form %}
<div class="form-group">
    {% if field.errors %}
    <div class="mypadding2 bg-red fg-white margin10 no-margin-right no-margin-left">
        <i class="fa fa-exclamation-triangle"></i>{{ field.errors }}
    </div>
    {% endif %}
    {% if field.html_name == 'origen' %}
    {{ field.label_tag }}
    <div class="col-sm-8">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    <div class="col-sm-1" style="line-height: 30px">
        <a href="{% url 'cliente-new-ciudad-popup' %}" class="btn btn-success add-another" title="Registrar Ciudad" id="{{ field.auto_id }}">
            <i class="fa fa-plus-circle "></i>
        </a>
    </div>
    {% else %}
    {% if field.html_name == 'pais' %}
    {{ field.label_tag }}
    <div class="col-sm-8">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    <div class="col-sm-1" style="line-height: 30px">
        <a href="{% url 'cliente-new-pais-popup' %}" class="btn btn-success add-another" title="Registrar Pais" id="{{ field.auto_id }}">
            <i class="fa fa-plus-circle "></i>
        </a>
    </div>
    {% else %}
    {{ field.label_tag }}
    <div class="col-sm-9">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    {% endif %}
    {% endif%}
</div>
{% endfor %}
{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $('#id_pais').change(medida);
        function medida(){
            if($(this).val()){
                var id = $(this).val();
                $.ajax({
                    data:{'id': id},
                    url:"{% url 'cliente-ajax-ciudades' %}",
                    type:'GET',
                    success: function(data){
                        $('#id_origen').html(data);
                    },
                    failure: function(data){
                        console.log('error')
                    }
                });
            }
        }
    });
</script>
{% include '__popup_script.html' %}
{% endblock %}

regalias/regalias/templates/proveedores/new_popup.html
{% extends '__form_popup.html' %}

{% block title %}
Registrar Proveedor
{% endblock %}

{% block legend %}
Registrar Proveedor
{% endblock %}

{% block cuerpo-form %}
{% for field in form %}
<div class="form-group">
    {% if field.errors %}
    <div class="mypadding2 bg-red fg-white margin10 no-margin-right no-margin-left">
        <i class="fa fa-exclamation-triangle"></i>{{ field.errors }}
    </div>
    {% endif %}
    {% if field.html_name == 'origen' %}
    {{ field.label_tag }}
    <div class="col-sm-8">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    <div class="col-sm-1" style="line-height: 30px">
        <a href="{% url 'cliente-new-ciudad-popup' %}" class="btn btn-success add-another" title="Registrar Ciudad" id="{{ field.auto_id }}">
            <i class="fa fa-plus-circle "></i>
        </a>
    </div>
    {% else %}
    {% if field.html_name == 'pais' %}
    {{ field.label_tag }}
    <div class="col-sm-8">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    <div class="col-sm-1" style="line-height: 30px">
        <a href="{% url 'cliente-new-pais-popup' %}" class="btn btn-success add-another" title="Registrar Pais" id="{{ field.auto_id }}">
            <i class="fa fa-plus-circle "></i>
        </a>
    </div>
    {% else %}
    {{ field.label_tag }}
    <div class="col-sm-9">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    {% endif %}
    {% endif%}
</div>
{% endfor %}
{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $('#id_pais').change(medida);
        function medida(){
            if($(this).val()){
                var id = $(this).val();
                $.ajax({
                    data:{'id': id},
                    url:"{% url 'cliente-ajax-ciudades' %}",
                    type:'GET',
                    success: function(data){
                        $('#id_origen').html(data);
                    },
                    failure: function(data){
                        console.log('error')
                    }
                });
            }
        }
    });
</script>
{% include '__popup_script.html' %}
{% endblock %}

regalias/regalias/templates/proveedores/pdf_proveedores.html
{% extends 'report.html' %}

{% block title %}
Proveedores
{% endblock %}

{% block cuerpo %}
<h2 align="center">DETALLE DE PROVEEDORES</h2>
<table >
    {% for proveedor in proveedores  %}
    <div> 
        <tr>
            <th class="celdas" colspan="4" width="100%" align="left" style="font-family: courier; font-size:15px; border: white;background-color:#d7d7d7;"> {{ forloop.counter }} DATOS DE: {{proveedor.proveedor|upper}} <strong></strong> </th>
        </tr>
        <tr></tr>
        <tr  style="font-family: courier; font-size:12px;">

            <td width="17%">
                <p> <strong> NOMBRE: </strong></br>
                   <strong> NIT/C.I. </strong></br>
                   <strong> PAÍS / CIUDAD: </strong></br>
               </p>
           </td>
           <td width="35%">            
            <p> {{ proveedor.proveedor |upper}}</br>
                {{ proveedor.nit |upper}}</br>
                {{ proveedor.origen.pais |upper}} / {{ proveedor.origen |upper}} </br>
            </p>
            </td>
            <td width="12%">
                <p>
                    <strong> DIRECIÓN: </strong></br>
                    <strong> TELÉFONO: </strong> </br>
                    <strong> EMAIL: </strong></br>
                </p>
            </td>
            <td width="36%">
                        <p>{{ proveedor.direccion |upper}} </br>
                        {{ proveedor.telefono |upper}}</br>
                    {{ proveedor.email}} </br>
                    </p>
            </td>
            {% endfor %}
        </tr>
    </div>
</table>
{% endblock %}

regalias/regalias/templates/proveedores/update.html
{% extends '__form.html' %}

{% block title %}
Modificar Proveedor
{% endblock %}

{% block legend %}
Modificar Proveedor
{% endblock %}

{% block submit %}
Modificar
{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $('#id_pais').change(medida);
        function medida(){
            if($(this).val()){
                var id = $(this).val();

                $.ajax({
                    data:{'id': id},
                    url:"{% url 'cliente-ajax-ciudades' %}",
                    type:'GET',
                    success: function(data){
                        $('#id_origen').html(data);
                    },
                    failure: function(data){
                        console.log('error')
                    }
                });
            }
        }
    });
</script>
{% endblock %}

regalias/regalias/templates/proveedores/update_proveedor_popup.html
{% extends '__form_popup.html' %}

{% block title %}
Modificar Proveedor
{% endblock %}

{% block legend %}
Modificar Proveedor
{% endblock %}

{% block submit %}
Modificar
{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $('#id_pais').change(medida);
        function medida(){
            if($(this).val()){
                var id = $(this).val();

                $.ajax({
                    data:{'id': id},
                    url:"{% url 'cliente-ajax-ciudades' %}",
                    type:'GET',
                    success: function(data){
                        $('#id_origen').html(data);
                    },
                    failure: function(data){
                        console.log('error')
                    }
                });
            }
        }
    });
</script>
{% endblock %}