regalias/clientes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='cliente-index'),
    path('new/ciudad', views.new_ciudad, name='cliente-new-ciudad'),
    path('popup/new/ciudad', views.new_ciudad_popup, name='cliente-new-ciudad-popup'),
    path('new/pais', views.new_pais, name='cliente-new-pais'),
    path('popup/new/pais', views.new_pais_popup, name='cliente-new-pais-popup'),
    path('new', views.new, name='cliente-new'),
    path('popup/new', views.new_cliente_popup, name='cliente-new-popup'),
        path('popup/<int:cliente_id>/update', views.update_cliente_popup, name='update_cliente_popup'),
    path('<int:cliente_id>/update', views.update, name='cliente-update'),
    path('<int:cliente_id>/baja', views.baja_cliente, name='cliente-baja'),
    path('<int:cliente_id>/activate', views.activate_cliente, name='cliente-activate'),
    path('<int:cliente_id>/detail', views.detail_cliente, name='cliente-detail'),
    path('list/bajas', views.baja_clientes, name='cliente-list-bajas'),
    path('pdf/clientes', views.pdf_clientes, name='cliente-pdf'),


    path('ajax/ciudades', views.ajax_ciudades, name='cliente-ajax-ciudades'),
]

regalias/regalias/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings

from users.views import home


urlpatterns = [
    path('media/(<path>)', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/(<path>)', serve, {'document_root': settings.STATIC_ROOT}),
    path('', home, name='index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('cliente/', include('clientes.urls')),
    path('materia/prima/', include('materiales.urls')),
    path('pedido/', include('pedidos.urls')),
    path('venta/', include('ventas.urls')),
    path('reporte/', include('reportes.urls')),
]

regalias/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('new/', views.user_creation, name='user-new'),
    path('update/', views.update_information, name='user-complete-information'),
    path('users/index', views.user_index, name='users-index'),
    path('change/pass/', views.reset_pass, name='user-reset-pass'),
    path('change/username/', views.change_username, name='user-change-username'),
    path('user/lista/', views.lista_usuarios, name='user-list'),
    path('user/<int:user_id>/baja/', views.baja_user, name='user-baja'),
    path('user/<int:user_id>/admin/activate/', views.activate_superuser, name='user-admin-activate'),
    path('user/<int:user_id>/admin/baja/', views.deactivate_superuser, name='user-admin-baja'),
    path('user/<int:user_id>/activate/', views.activate_user, name='user-activate'),
    path('<int:user_id>/permission/', views.permisos, name='user-permission'),
    path('add/<int:grupo_id>/<int:user_id>/permission/', views.add_grupo, name='user-add-permission'),
    path('remove/<int:grupo_id>/<int:user_id>/permission/', views.remove_grupo, name='user-remove-permission'),


    path('user/<int:user_id>/ventas', views.ventas_user, name='user-ventas'),
    path('user/<int:user_id>/pdf/<int:iyear>/<int:imonth>/<int:iday>/ventas/<int:fyear>/<int:fmonth>/<int:fday>', views.pdf_ventas_user, name='user-pdf-ventas-fechas'),

    path('mis/ventas', views.mis_ventas, name='mis-ventas'),
    path('mis/ventas/pdf/<int:iyear>/<int:imonth>/<int:iday>/ventas/<int:fyear>/<int:fmonth>/<int:fday>', views.pdf_misventas, name='user-pdf-mis_ventas-fechas'),

    path('empresa', views.info_empresa, name='empresa_info'),
    path('empresa/new', views.new_empresa, name='empresa_new'),
    path('empresa/update', views.update_empresa, name='empresa_update'),

    path('color', views.index_colores, name='color-index'),
    path('color/new', views.new_color, name='color-new'),
    path('color/<int:color_id>/update', views.update_color, name='color-update'),
    path('color/new/popup', views.new_color_popup, name='color-new-popup'),

    path('color/name/ajax', views.color_ajax, name='color-ajax'),

]

regalias/clientes/models.py
from __future__ import unicode_literals
from django.db import models

from django.core.exceptions import ValidationError

def validate_ci(value):
    if len(str(value)) != 10 and len(str(value)) != 8 and len(str(value)) != 7:
        raise ValidationError(u'%s No es un Cedula de Identidad'% value)
    return validate_ci

GENERO = (
    ('Masculino','Masculino'),
    ('Femenino', 'Femenino'),
)

class Pais(models.Model):
    pais = models.CharField(max_length=30, verbose_name='Nombre', unique=True)
    def __str__(self):
        return self.pais
    def __unicode__(self):
        return self.pais
    class Meta:
        ordering = ['pais']
        verbose_name = 'País'
        verbose_name_plural = 'Paices'

class Ciudad(models.Model):
    ciudad = models.CharField(max_length=30, verbose_name='Nombre', unique=True)
    pais = models.ForeignKey(Pais, on_delete=models.PROTECT)
    def __str__(self):
        return self.ciudad
    def __unicode__(self):
        return self.ciudad
    class Meta:
        ordering = ['pais', 'ciudad']
        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'


class Cliente(models.Model):
    nit = models.CharField(max_length=20, verbose_name='NIT/CI', null=True, unique=True)
    razon = models.CharField(max_length=100, verbose_name='Nombre o Razon Social', null=True)
    direccion = models.CharField(max_length=50, verbose_name='Direccion')
    telefono = models.CharField(max_length=15, verbose_name='Telefono/Ceular')
    email = models.EmailField(blank=True, verbose_name='Correo Electronico')
    ciudad = models.ForeignKey(Ciudad, verbose_name='Ciudad', on_delete=models.PROTECT)
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s %s' % (self.nit, self.razon)
    def __str__(self):
        return '%s %s' % (self.nit, self.razon)

regalias/clientes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse, Http404, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.template import RequestContext
from django.template.loader import render_to_string
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, AdminPasswordChangeForm
from django.conf import settings
from django.db.models import ProtectedError

from regalias.utility import admin_log_addition, admin_log_change, render_pdf

from clientes.models import Pais, Ciudad, Cliente
from clientes.form import ClienteForm, CiudadForm, PaisForm

@login_required(login_url='/login/')
def index(request):
    clientes = Cliente.objects.filter(estado=True)
    return render(request, 'clientes/index.html', {
        'clientes':clientes,
    })

@login_required(login_url='/login/')
def new_pais(request):
    if request.method == 'POST':
        form = PaisForm(request.POST)
        if form.is_valid():
            p = form.save()
            admin_log_addition(request, p, 'Pais Creado')
            messages.success(request, 'Pais Registrado Correctamente')
            return HttpResponseRedirect(reverse(index))
    else:
        form = PaisForm()
    return render(request, 'clientes/new_pais.html', {
        'form':form,
    })

@login_required(login_url='/login/')
def new_ciudad(request):
    ref = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = CiudadForm(request.POST)
        if form.is_valid():
            c = form.save()
            admin_log_addition(request, c, 'Ciudad Creada')
            messages.success(request, 'Ciudad Registrada Correctamente')
            return HttpResponseRedirect(reverse(index))
    else:
        form = CiudadForm()
    return render(request, 'clientes/new_ciudad.html', {
        'form':form,
    })

@login_required(login_url='/login/')
def new(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            c = form.save()
            admin_log_addition(request, c, 'Cliente Creado')
            messages.success(request, 'Cliente Registrado Correctamente')
            return HttpResponseRedirect(reverse(index))
    else:
        form = ClienteForm()
    return render(request, 'clientes/new.html', {
        'form':form,
    })

@login_required(login_url='/login/')
def ajax_ciudades(request):
    if request.is_ajax():
        pais = get_object_or_404(Pais, pk = request.GET['id'])
        ciudades = Ciudad.objects.filter(pais=pais)
        html = render_to_string('clientes/__ajax_ciudades.html', {
            'ciudades':ciudades,
        })
        return JsonResponse(html, safe=False)
    else:
        raise Http404

@login_required(login_url='/login/')
def update(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk = cliente_id)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            c = form.save()
            admin_log_addition(request, c, 'Cliente Modificado')
            messages.warning(request, 'Cliente Modificado Correctamente')
            return HttpResponseRedirect(reverse(index))
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'clientes/update.html', {
        'form':form,
    })

@login_required(login_url='/login/')
def detail_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    return render(request, 'clientes/detail.html', {
        'cliente':cliente,
    })

@login_required(login_url='/login/')
def baja_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk = cliente_id)
    cliente.estado = False
    cliente.save()
    admin_log_change(request, cliente, 'Cliente Dado de Baja')
    messages.warning(request, 'Cliente Dado de Baja')
    return HttpResponseRedirect(reverse(index))

@login_required(login_url='/login/')
def baja_clientes(request):
    clientes = Cliente.objects.filter(estado = False)
    return render(request, 'clientes/baja_clientes.html', {
        'clientes':clientes,
    })

@login_required(login_url='/login/')
def activate_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    cliente.estado = True
    cliente.save()
    admin_log_change(request, cliente, 'Cliente Activado')
    messages.info(request, 'Cliente Activado')
    return HttpResponseRedirect(reverse(baja_clientes))

@login_required(login_url='/login/')
def pdf_clientes(request):
    clientes = Cliente.objects.filter(estado=True)
    html = render_to_string('clientes/pdf_clientes.html ', {
        'clientes':clientes,
    })
    return render_pdf(html)

@login_required(login_url='/login/')
def new_ciudad_popup(request):
    if request.method == 'POST':
        form = CiudadForm(request.POST)
        if form.is_valid():
            c = form.save()
            admin_log_addition(request, c, 'Ciudad Creada')
            return render(request, 'close_popup.html', {
                'c':c,
            })
    else:
        form = CiudadForm()
    return render(request, 'clientes/new_ciudad_popup.html', {
        'form':form,
    })

@login_required(login_url='/login/')
def new_pais_popup(request):
    if request.method == 'POST':
        form = PaisForm(request.POST)
        if form.is_valid():
            p = form.save()
            admin_log_addition(request, p, 'Pais Creado')
            return render(request, 'close_popup.html', {
                'c':p,
            })
    else:
        form = PaisForm()
    return render(request, 'clientes/new_pais_popup.html', {
        'form':form,
    })

@login_required(login_url='/login/')
def new_cliente_popup(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            p = form.save()
            admin_log_addition(request, p, 'Cliente Creado')
            return render(request, 'close_popup.html', {
                'c':p,
            })
    else:
        form = ClienteForm()
    return render(request, 'clientes/new_cliente_popup.html', {
        'form':form,
    })

@login_required(login_url='/login/')
def update_cliente_popup(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk = cliente_id)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            p = form.save()
            admin_log_addition(request, p, 'Cliente Modificado')
            messages.warning(request, 'Cliente Modificado Correctamente')
            return render(request, 'close_popup.html', {
            })
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'clientes/update_cliente_popup.html', {
        'form':form,
    })

regalias/regalias/templates/clientes/__ajax_ciudades.html
<option value="">---------</option>
{% for ciudad in ciudades %}
<option value="{{ ciudad.id }}">{{ ciudad.ciudad }}</option>
{% endfor %}

regalias/regalias/templates/clientes/baja_clientes.html
{% extends 'base.html' %}

{% block title %}
Nuestros Clientes
{% endblock %}

{% block content %}
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2 class="app">Clientes Bajas <small style="font-family:arial">Lista de Clientes </small></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li><a class="close-link" href=""><i class="fa fa-close"></i></a>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<div class="x_content">
  <p class="text-muted font-13 m-b-30">
    Este es una tabla donde contiene los datos de los clientes registrados que estan dados de baja.
</p>
<div class="">
    <table class="table striped hovered border bordered" width="100%">
        <thead>
            <tr>
                <th width="30px">#</th>
                <th>C.I. / NIT</th>
                <th>NOMBRE O RAZON SOCIAL</th>
                <th>TELÉFONO</th>
                <th>DIRECCIÓN</th>
                <th>PAÍS / CIUDAD</th>
                
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ cliente.nit }}</td>
                <td>{{ cliente.razon |upper}}</td>
                <td>{{ cliente.telefono |upper}}</td>
                <td>{{ cliente.direccion |upper}}</td>
                <td>{{ cliente.ciudad.pais |upper}} / {{ cliente.ciudad |upper}}</td>
                <td>
                    <a href="{% url 'cliente-activate' cliente.id %}" class="btn btn-success btn-xs" title="Activar Cliente">
                        <i class="fa fa-check-square"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>
</div>
{% endblock %}

regalias/regalias/templates/clientes/detail.html
{% extends 'base.html' %}

{% block title %}
Detalle Cliente
{% endblock %}

{% block content %}
<div class="row">
    <h1>Detalle Cliente</h1>
    <div class="col-md-6">
        <p class="lead">
            <strong>Nombre Completo: </strong>{{ cliente.nombres }} {{ cliente.apellidos }}
        </p>
        <p class="lead">
            <strong>Cedula de Identidad: </strong>{{ cliente.ci }}
        </p>
        <p class="lead">
            <strong>Telefono: </strong>{{ cliente.telefono }}
        </p>
    </div>
    <div class="col-md-6">
        <p class="lead">
            <strong>Pais / Ciudad: </strong>{{ cliente.ciudad.pais }} / {{ cliente.ciudad }}
        </p>
        <p class="lead">
            <strong>Email: </strong>{{ cliente.email }}
        </p>
        <p class="lead">
            <strong>Direccion: </strong>{{ cliente.direccion }}
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <a href="{% url 'cliente-baja' cliente.id %}" class="btn btn-danger">
            <span class="fa fa-times-circle"></span> Baja Cliente
        </a>
    </div>
</div>
{% endblock %}

regalias/regalias/templates/clientes/new.html
{% extends '__form.html' %}

{% block title %}
Registrar Cliente
{% endblock %}

{% block legend %}
Registrar Cliente
{% endblock %}

{% block cuerpo-form %}
{% for field in form %}
<div class="form-group">
    {% if field.errors %}
    <div class="mypadding2 bg-red fg-white margin10 no-margin-right no-margin-left">
        <i class="fa fa-exclamation-triangle"></i>{{ field.errors }}
    </div>
    {% endif %}
    {% if field.html_name == 'ciudad' %}
    {{ field.label_tag }}
    <div class="col-sm-8">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    <div class="col-sm-1" style="line-height: 30px">
        <a href="{% url 'cliente-new-ciudad-popup' %}" class="btn btn-success add-another" title="Registrar Ciudad" id="{{ field.auto_id }}">
            <i class="fa fa-plus-circle "></i>
        </a>
    </div>
    {% else %}
    {% if field.html_name == 'pais' %}
    {{ field.label_tag }}
    <div class="col-sm-8">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    <div class="col-sm-1" style="line-height: 30px">
        <a href="{% url 'cliente-new-pais-popup' %}" class="btn btn-success add-another" title="Registrar Pais" id="{{ field.auto_id }}">
            <i class="fa fa-plus-circle "></i>
        </a>
    </div>
    {% else %}
    {{ field.label_tag }}
    <div class="col-sm-9">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    {% endif %}
    {% endif%}
</div>
{% endfor %}
{% endblock %}

{% block js %}
<script>
$(document).ready(function () {
    $('#id_pais').change(medida);
    function medida(){
        if($(this).val()){
            var id = $(this).val();
            $.ajax({
                data:{'id': id},
                url:"{% url 'cliente-ajax-ciudades' %}",
                type:'GET',
                success: function(data){
                    $('#id_ciudad').html(data);
                },
                failure: function(data){
                    console.log('error')
                }
            });
        }
    }
});
</script>
{% include '__popup_script.html' %}
{% endblock %}

regalias/regalias/templates/clientes/new_ciudad.html
{% extends '__form.html' %}

{% block title %}
Nueva Ciudad
{% endblock %}

{% block legend %}
Registrar Ciudad
{% endblock %}

{% block cuerpo-form %}
{% for field in form %}
    <div class="form-group">
        {% if field.errors %}
            <div class="mypadding2 bg-red fg-white margin10 no-margin-right no-margin-left">
                <i class="fa fa-exclamation-triangle"></i>{{ field.errors }}
            </div>
        {% endif %}
        {% if field.html_name == 'pais' %}
            {{ field.label_tag }}
            <div class="col-sm-8">
                {{ field }}
                {% if field.help_text %}
                    <small class="fg-green block padding10 no-padding-top">
                        <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
                    </small>
                {% endif %}
            </div>
            <div class="col-sm-1" style="line-height: 30px">
                <a href="{% url 'cliente-new-pais-popup' %}" class="btn btn-success add-another" title="Registrar Pais" id="{{ field.auto_id }}">
                    <i class="fa fa-plus-circle "></i>
                </a>
            </div>
        {% else %}
            {{ field.label_tag }}
            <div class="col-sm-9">
                {{ field }}
                {% if field.help_text %}
                    <small class="fg-green block padding10 no-padding-top">
                        <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
                    </small>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endfor %}
{% endblock %}

{% block js %}
{% include '__popup_script.html' %}
{% endblock %}

regalias/regalias/templates/clientes/new_ciudad_popup.html
{% extends '__form_popup.html' %}

{% block title %}
Nueva Ciudad
{% endblock %}

{% block legend %}
Registrar Ciudad
{% endblock %}

{% block cuerpo-form %}
{% for field in form %}
    <div class="form-group">
        {% if field.errors %}
            <div class="mypadding2 bg-red fg-white margin10 no-margin-right no-margin-left">
                <i class="fa fa-exclamation-triangle"></i>{{ field.errors }}
            </div>
        {% endif %}
        {% if field.html_name == 'pais' %}
            {{ field.label_tag }}
            <div class="col-sm-8">
                {{ field }}
                {% if field.help_text %}
                    <small class="fg-green block padding10 no-padding-top">
                        <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
                    </small>
                {% endif %}
            </div>
            <div class="col-sm-1" style="line-height: 30px">
                <a href="{% url 'cliente-new-pais-popup' %}" class="btn btn-success add-another" title="Registrar Pais" id="{{ field.auto_id }}">
                    <i class="fa fa-plus-circle "></i>
                </a>
            </div>
        {% else %}
            {{ field.label_tag }}
            <div class="col-sm-9">
                {{ field }}
                {% if field.help_text %}
                    <small class="fg-green block padding10 no-padding-top">
                        <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
                    </small>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endfor %}
{% endblock %}

{% block js %}
{% include '__popup_script.html' %}
{% endblock %}

regalias/regalias/templates/clientes/new_cliente_popup.html
{% extends '__form_popup.html' %}

{% block title %}
Nuevo Cliente
{% endblock %}

{% block legend %}
Registrar Cliente
{% endblock %}

{% block cuerpo-form %}
{% for field in form %}
<div class="form-group">
    {% if field.errors %}
    <div class="mypadding2 bg-red fg-white margin10 no-margin-right no-margin-left">
        <i class="fa fa-exclamation-triangle"></i>{{ field.errors }}
    </div>
    {% endif %}
    {% if field.html_name == 'ciudad' %}
    {{ field.label_tag }}
    <div class="col-sm-8">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    <div class="col-sm-1" style="line-height: 30px">
        <a href="{% url 'cliente-new-ciudad-popup' %}" class="btn btn-success add-another" title="Registrar Ciudad" id="{{ field.auto_id }}">
            <i class="fa fa-plus-circle "></i>
        </a>
    </div>
    {% else %}
    {% if field.html_name == 'pais' %}
    {{ field.label_tag }}
    <div class="col-sm-8">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    <div class="col-sm-1" style="line-height: 30px">
        <a href="{% url 'cliente-new-pais-popup' %}" class="btn btn-success add-another" title="Registrar Pais" id="{{ field.auto_id }}">
            <i class="fa fa-plus-circle "></i>
        </a>
    </div>
    {% else %}
    {{ field.label_tag }}
    <div class="col-sm-9">
        {{ field }}
        {% if field.help_text %}
        <small class="fg-green block padding10 no-padding-top">
            <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    {% endif %}
    {% endif%}
</div>
{% endfor %}
{% endblock %}

{% block js %}
<script>
$(document).ready(function () {
    $('#id_pais').change(medida);
    function medida(){
        if($(this).val()){
            var id = $(this).val();
            $.ajax({
                data:{'id': id},
                url:"{% url 'cliente-ajax-ciudades' %}",
                type:'GET',
                success: function(data){
                    $('#id_ciudad').html(data);
                },
                failure: function(data){
                    console.log('error')
                }
            });
        }
    }
});
</script>
{% include '__popup_script.html' %}
{% endblock %}

regalias/regalias/templates/clientes/new_pais.html
{% extends '__form.html' %}

{% block title %}
Nueva Ciudad
{% endblock %}

{% block legend %}
Registrar Ciudad
{% endblock %}

{% block cuerpo-form %}
{% for field in form %}
    <div class="form-group">
        {% if field.errors %}
            <div class="mypadding2 bg-red fg-white margin10 no-margin-right no-margin-left">
                <i class="fa fa-exclamation-triangle"></i>{{ field.errors }}
            </div>
        {% endif %}
        {% if field.html_name == 'ciudad' %}
            {{ field.label_tag }}
            <div class="col-sm-8">
                {{ field }}
                {% if field.help_text %}
                    <small class="fg-green block padding10 no-padding-top">
                        <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
                    </small>
                {% endif %}
            </div>
            <div class="col-sm-1" style="line-height: 30px">
                <a href="{% url 'cliente-new-ciudad-popup' %}" class="btn btn-success add-another" title="Registrar Ciudad" id="{{ field.auto_id }}">
                    <i class="fa fa-plus-circle "></i>
                </a>
            </div>
        {% else %}
            {{ field.label_tag }}
            <div class="col-sm-9">
                {{ field }}
                {% if field.help_text %}
                    <small class="fg-green block padding10 no-padding-top">
                        <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
                    </small>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endfor %}
{% endblock %}

{% block js %}
{% include '__popup_script.html' %}
{% endblock %}

regalias/regalias/templates/clientes/new_pais_popup.html
{% extends '__form_popup.html' %}

{% block title %}
Nueva Ciudad
{% endblock %}

{% block legend %}
Registrar Ciudad
{% endblock %}

regalias/regalias/templates/clientes/new_popup.html
{% extends '__form_popup.html' %}

{% block title %}
Registrar Cliente
{% endblock %}

{% block legend %}
Registrar Cliente
{% endblock %}

{% block js %}
<script>
(function($) {
    'use strict';
    var fields = $('#django-admin-prepopulated-fields-constants').data('prepopulatedFields');
    $.each(fields, function(index, field) {
        $('.empty-form .form-row .field-' + field.name + ', .empty-form.form-row .field-' + field.name).addClass('prepopulated_field');
        $(field.id).data('dependency_list', field.dependency_list).prepopulate(
            field.dependency_ids, field.maxLength, field.allowUnicode
        );
    });
})(django.jQuery);
    $(document).ready(function () {
        $('#id_pais').change(medida);
        function medida(){
            if($(this).val()){
                var id = $(this).val();
                $.ajax({
                    data:{'id': id},
                    url:"{% url 'cliente-ajax-ciudades' %}",
                    type:'GET',
                    success: function(data){
                        $('#id_ciudad').html(data);
                    },
                    failure: function(data){
                        console.log('error')
                    }
                });
            }
        }
    });
</script>
{% endblock %}

regalias/regalias/templates/clientes/update.html
{% extends '__form.html' %}

{% block title %}
Modificar Cliente
{% endblock %}

{% block legend %}
Modificar Cliente
{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $('#id_pais').change(medida);
        function medida(){
            if($(this).val()){
                var id = $(this).val();
                $.ajax({
                    data:{'id': id},
                    url:"{% url 'cliente-ajax-ciudades' %}",
                    type:'GET',
                    success: function(data){
                        $('#id_ciudad').html(data);
                    },
                    failure: function(data){
                        console.log('error')
                    }
                });
            }
        }
    });
</script>
{% endblock %}

regalias/regalias/templates/clientes/update_cliente_popup.html
{% extends '__form_popup.html' %}

{% block title %}
Registrar Cliente
{% endblock %}

{% block legend %}
Modificar Cliente
{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $('#id_pais').change(medida);
        function medida(){
            if($(this).val()){
                var id = $(this).val();
                $.ajax({
                    data:{'id': id},
                    url:"{% url 'cliente-ajax-ciudades' %}",
                    type:'GET',
                    success: function(data){
                        $('#id_ciudad').html(data);
                    },
                    failure: function(data){
                        console.log('error')
                    }
                });
            }
        }
    });
</script>
{% endblock %}