regalias/regalias/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings

from users.views import home


urlpatterns = [
    path('media/(<path>)', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/(<path>)', serve, {'document_root': settings.STATIC_ROOT}),
    path('', home, name='index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('cliente/', include('clientes.urls')),
    path('materia/prima/', include('materiales.urls')),
    path('pedido/', include('pedidos.urls')),
    path('venta/', include('ventas.urls')),
    path('reporte/', include('reportes.urls')),
]

regalias/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('new/', views.user_creation, name='user-new'),
    path('update/', views.update_information, name='user-complete-information'),
    path('users/index', views.user_index, name='users-index'),
    path('change/pass/', views.reset_pass, name='user-reset-pass'),
    path('change/username/', views.change_username, name='user-change-username'),
    path('user/lista/', views.lista_usuarios, name='user-list'),
    path('user/<int:user_id>/baja/', views.baja_user, name='user-baja'),
    path('user/<int:user_id>/admin/activate/', views.activate_superuser, name='user-admin-activate'),
    path('user/<int:user_id>/admin/baja/', views.deactivate_superuser, name='user-admin-baja'),
    path('user/<int:user_id>/activate/', views.activate_user, name='user-activate'),
    path('<int:user_id>/permission/', views.permisos, name='user-permission'),
    path('add/<int:grupo_id>/<int:user_id>/permission/', views.add_grupo, name='user-add-permission'),
    path('remove/<int:grupo_id>/<int:user_id>/permission/', views.remove_grupo, name='user-remove-permission'),


    path('user/<int:user_id>/ventas', views.ventas_user, name='user-ventas'),
    path('user/<int:user_id>/pdf/<int:iyear>/<int:imonth>/<int:iday>/ventas/<int:fyear>/<int:fmonth>/<int:fday>', views.pdf_ventas_user, name='user-pdf-ventas-fechas'),

    path('mis/ventas', views.mis_ventas, name='mis-ventas'),
    path('mis/ventas/pdf/<int:iyear>/<int:imonth>/<int:iday>/ventas/<int:fyear>/<int:fmonth>/<int:fday>', views.pdf_misventas, name='user-pdf-mis_ventas-fechas'),

    path('empresa', views.info_empresa, name='empresa_info'),
    path('empresa/new', views.new_empresa, name='empresa_new'),
    path('empresa/update', views.update_empresa, name='empresa_update'),

    path('color', views.index_colores, name='color-index'),
    path('color/new', views.new_color, name='color-new'),
    path('color/<int:color_id>/update', views.update_color, name='color-update'),
    path('color/new/popup', views.new_color_popup, name='color-new-popup'),

    path('color/name/ajax', views.color_ajax, name='color-ajax'),

]

regalias/ventas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='venta-index'),
    path('new/clientes', views.new_list_cliente, name='venta-list-clientes'),
    path('new/<int:cliente_id>/', views.new_venta, name='venta-new'),
    path('new/<int:venta_id>/detail', views.new_detail_venta, name='venta-new-detail'),
    path('new/<int:venta_id>/add/material', views.add_material, name='venta-new-add-material'),
    path('new/<int:detalle_id>/delete/material', views.delete_material, name='venta-new-delete-material'),
    path('confirm/<int:venta_id>', views.confirm_venta, name='venta-confirm'),

    path('no/confirm/', views.ventas_no_confirmados, name='venta-no-confirmados'),
    path('<int:venta_id>/delete', views.delete_venta, name='venta-delete'),
    path('<int:venta_id>/detail', views.detail_venta, name='venta-detail'),
    path('pedidos/', views.list_pedidos, name='venta-list-pedidos'),
    path('pedido/<int:pedido_id>/detail', views.detail_pedido_venta, name='venta-pedido-detail'),
    path('pedido/<int:pedido_id>/vent/', views.venta_pedido, name='venta-pedido-vent'),

    path('pdf/<int:venta_id>/detail', views.pdf_detail_venta, name='venta-pdf-detail'),
    path('pdf/<int:venta_id>/recibo', views.pdf_recibo_venta, name='venta-pdf-recibo'),


    path('pdf/<int:venta_id>/factura', views.factura_pdf, name='venta-pdf-factura'),


    path('ajax/precio/clavo', views.ajax_get_precio, name='venta-ajax-precio-clavo'),

    path('calamina/new/clientes', views.calamina_new_list_cliente, name='venta-list-clientes-calamina'),
    path('calamina/new/<int:cliente_id>/', views.calamina_new_venta, name='venta-new-calamina'),
    path('calamina/new/<int:venta_id>/detail', views.calamina_new_detail_venta, name='venta-new-detail-calamina'),

    path('calamina/add/new/material/<int:venta_id>/calamina', views.add_new_material_calamina, name='venta-new-add-material-calamina-new'),

    path('calamina/new/<int:venta_id>/add/material', views.calamina_add_material, name='venta-new-add-material-calamina'),
    path('calamina/<int:detalle_id>/delete', views.calamina_delete_material, name='venta-delete-calamina'),

    path('ajax/calamina/precio/', views.ajax_get_precio_calamina, name='pedido-ajax-precio-calamina'),
    path('ajax/calamina/material/color', views.ajax_get_materiales_calamina, name='pedido-ajax-material-calamina'),


    path('ajax/preiciocalamina/material', views.ajax_precio_calamina, name='pedido-ajax-precio-calamina'),

]

regalias/clientes/models.py
from __future__ import unicode_literals
from django.db import models

from django.core.exceptions import ValidationError

def validate_ci(value):
    if len(str(value)) != 10 and len(str(value)) != 8 and len(str(value)) != 7:
        raise ValidationError(u'%s No es un Cedula de Identidad'% value)
    return validate_ci

GENERO = (
    ('Masculino','Masculino'),
    ('Femenino', 'Femenino'),
)

class Pais(models.Model):
    pais = models.CharField(max_length=30, verbose_name='Nombre', unique=True)
    def __str__(self):
        return self.pais
    def __unicode__(self):
        return self.pais
    class Meta:
        ordering = ['pais']
        verbose_name = 'País'
        verbose_name_plural = 'Paices'

class Ciudad(models.Model):
    ciudad = models.CharField(max_length=30, verbose_name='Nombre', unique=True)
    pais = models.ForeignKey(Pais, on_delete=models.PROTECT)
    def __str__(self):
        return self.ciudad
    def __unicode__(self):
        return self.ciudad
    class Meta:
        ordering = ['pais', 'ciudad']
        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'


class Cliente(models.Model):
    nit = models.CharField(max_length=20, verbose_name='NIT/CI', null=True, unique=True)
    razon = models.CharField(max_length=100, verbose_name='Nombre o Razon Social', null=True)
    direccion = models.CharField(max_length=50, verbose_name='Direccion')
    telefono = models.CharField(max_length=15, verbose_name='Telefono/Ceular')
    email = models.EmailField(blank=True, verbose_name='Correo Electronico')
    ciudad = models.ForeignKey(Ciudad, verbose_name='Ciudad', on_delete=models.PROTECT)
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s %s' % (self.nit, self.razon)
    def __str__(self):
        return '%s %s' % (self.nit, self.razon)

regalias/pedidos/models.py
from django.db import models
from django.contrib.auth.models import User

from clientes.models import Cliente
from materiales.models import MateriaPrima, PrecioCalamina

class Pedido(models.Model):
    fecha = models.DateField(auto_now_add=True)
    cliente = models.ForeignKey(Cliente, models.PROTECT)
    costo = models.FloatField(default=0)
    estado = models.BooleanField(default=False)
    venta = models.BooleanField(default=False)
    entrega = models.CharField(max_length=300, null=True, verbose_name='Lugar de Entrega', help_text='Direccion' )
    plazo = models.IntegerField(default=1, verbose_name='Plazo de Entrega', help_text='En Dias')
    nro_pedido = models.IntegerField(null=True)
    persona_entrega = models.CharField(max_length=100, null=True, verbose_name='Nombres y Apellidos', help_text='Persona de referencia para entrega')
    telefono_ref = models.IntegerField(verbose_name='Telefono Persona Referencia', null=True)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    
    def __unicode__(self):
        return '%s %s'%(self.fecha, self.cliente)
    def __str__(self):
        return '%s %s' % (self.fecha, self.cliente)
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        ordering = ['fecha', 'cliente']

MATERIALCHOICES = (
    ('Calamina', 'Calamina'),
    ('Clavos', 'Clavos'),
)

MATERIALUNIDAD = (
    ('Pieza', 'Pieza'),
    ('Kilos', 'Kilos'),
)

class DetallePedido(models.Model):
    preciocalamina = models.ForeignKey(PrecioCalamina, models.PROTECT, null=True)

    unidad = models.CharField(max_length=50, verbose_name='Unidad de Medida', default='Unidad', choices=MATERIALUNIDAD)
    descripcion = models.TextField(verbose_name='Descripcion Pedido')
    cantidad = models.IntegerField()
    largo = models.FloatField(null=True)
    costo_u = models.FloatField(default=0, verbose_name='Costo Unitario', help_text='En Bolivianos')
    costo_t = models.FloatField(verbose_name='Costo Total', help_text='En Bolivianos')
    pedido = models.ForeignKey(Pedido, models.PROTECT)
    material = models.ManyToManyField(MateriaPrima)
    color = models.CharField(max_length=100, null=True)
    ancho = models.FloatField(null=True)
    totalm = models.FloatField(null=True)
    tipo = models.CharField(max_length=50, null=True)

    #materiap = models.ForeignKey(MateriaPrima, on_delete=models.PROTECT, null=True)
    def __unicode__(self):
        return '%s: %s'%(self.pedido.id, self.cantidad)
    def __str__(self):
        return '%s: %s' % (self.pedido.id, self.cantidad)
    class Meta:
        verbose_name = 'Detalle Pedido'
        verbose_name_plural = 'Detalles Pedidos'
        ordering = ['pedido']

regalias/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

class Empresa(models.Model):
    nit = models.CharField(max_length=300, verbose_name='NIT Empresa')
    nro = models.CharField(max_length=300, verbose_name='Numero de Autorizacion')
    key = models.CharField(max_length=500, verbose_name='Llave de Dosificacion')
    vencimiento = models.DateField(null=True)
    sms = models.TextField(max_length=500, null=True, verbose_name='Mensaje de Factura')
    def __unicode__(self):
        return '%s'%self.nit
    def __str__(self):
        return '%s' % self.nit

class Color(models.Model):
    color = models.CharField(max_length=100, verbose_name='Descripcion de Color', unique=True)
    codigo = models.CharField(max_length=100, null=True)
    def __unicode__(self):
        return '%s'%self.color
    def __str__(self):
        return '%s' % self.color
    class Meta:
        verbose_name = 'Color'
        verbose_name_plural = 'Colores'
        ordering = ['color']

class ColorName(models.Model):
    nombre_c = models.CharField(max_length=50)
    hexa = models.CharField(max_length=20)

SEX = (
    ('Masculino', 'Masculino'),
    ('Femenino', 'Femenino'),
)
class Perfil(models.Model):
    direccion = models.CharField(max_length=100, verbose_name='Direccion', null=True)
    celular = models.IntegerField(verbose_name='Celular', null=True)
    sexo = models.CharField(max_length=50, choices=SEX, null=True)
    #avatar = models.ImageField(upload_to='avatar', verbose_name='Seleccione foto perfil')
    usuarios = models.OneToOneField(User, unique=True, on_delete=models.PROTECT, null=True)
    def __unicode__(self):
        return '%s'%(self.usuarios)
    def __str__(self):
        return '%s' % (self.usuarios)
    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

regalias/ventas/models.py
from django.db import models
from django.contrib.auth.models import User

from clientes.models import Cliente
from materiales.models import PrecioCalamina, PrecioClavos

class Venta(models.Model):
    fecha = models.DateField(auto_now_add=True)
    cliente = models.ForeignKey(Cliente, models.PROTECT)
    costo = models.FloatField(default=0)
    estado = models.BooleanField(default=False)
    nro_venta = models.IntegerField(null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    def __unicode__(self):
        return '%s %s'%(self.fecha, self.cliente)
    def __str__(self):
        return '%s %s' % (self.fecha, self.cliente)
    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'Ventas'
        ordering = ['fecha', 'cliente']

MATERIALCHOICES = (
    ('Calamina', 'Calamina'),
    ('Clavos', 'Clavos'),
)

MATERIALUNIDAD = (
    ('Kilos', 'Kilos'),
    ('Calamina', 'Calamina'),
)

from materiales.models import MateriaPrima

class DetalleVenta(models.Model):
    preciocalamina = models.ForeignKey(PrecioCalamina, models.PROTECT, null=True)
    precioclavos = models.ForeignKey(PrecioClavos, models.PROTECT, null=True)
    material = models.ManyToManyField(MateriaPrima)
    unidad = models.CharField(max_length=50, verbose_name='Unidad de Medida', default='Kilos', choices=MATERIALUNIDAD)
    descripcion = models.TextField(verbose_name='Descripción')
    cantidad = models.IntegerField()
    costo_u = models.FloatField(default=0, verbose_name='Costo Unitario')
    costo_t = models.FloatField(verbose_name='Costo Total')
    venta = models.ForeignKey(Venta, models.PROTECT)
    largo = models.FloatField(default=1, null=True)
    precio_id = models.IntegerField(null=True)
    tipo = models.CharField(max_length=50, null=True)
    totalm = models.FloatField(null=True) 
   
    #materia_id = models.ForeignKey(MateriaPrima, null=True, on_delete=models.PROTECT)
    def __unicode__(self):
        return '%s: %s'%(self.venta.id, self.cantidad)
    def __str__(self):
        return '%s: %s' % (self.venta.id, self.cantidad)
    def information(self):
        if self.preciocalamina:
            return '%s  %s mm.  x %s mm.' % (self.preciocalamina.tipo, self.preciocalamina.espesor, self.preciocalamina.ancho)
        else:
            return '%s' % (self.unidad)
    class Meta:
        verbose_name = 'Detalle Venta'
        verbose_name_plural = 'Detalle Ventas'
        ordering = ['venta', 'preciocalamina']

regalias/regalias/templates/ventas/calamina/add_material.html
{% extends '__form.html' %}

{% block title %}
Agregar Material
{% endblock %}

{% block info-form %}
{% include 'includes/__info_venta.html' %}
{% endblock %}

{% block legend %}
Agregar Material
{% endblock %}

{% block cuerpo-form %}
{% for field in form %}
    <div class="form-group">
        {% if field.errors %}
            <div class="mypadding2 bg-red fg-white margin10 no-margin-right no-margin-left">
                <i class="fa fa-exclamation-triangle"></i>{{ field.errors }}
            </div>
        {% endif %}
        {{ field.label_tag }}
        {% if field.html_name == 'cantidad' %}
            <div class="col-sm-6">
                {{ field }}
                {% if field.help_text %}
                    <small class="fg-green block padding10 no-padding-top">
                        <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
                    </small>
                {% endif %}
            </div>
            <div class="col-sm-3" id="informacionid" style="">

            </div>
        {% else %}
            <div class="col-sm-9">
            {{ field }}
            {% if field.help_text %}
                <small class="fg-green block padding10 no-padding-top">
                    <i class="fa fa-info-circle"></i> {{ field.help_text|safe }}
                </small>
            {% endif %}
        </div>
        {% endif %}
    </div>
{% endfor %}
{% endblock %}


{% block js %}
<script>
    $(document).ready(function () {
        var html = '';
        var mdisponibles = 0;
        {% for material in materiales %}
            html = html + '<option value="{{ material.color }}">{{ material.color }}</option>';
        {% endfor %}
        /*$('#id_color').html(html);*/
        var precio = 0;
        var cantidad = 0;
        var large = 0;
        var tmetros = 0;
        $('#id_calamina').change(function () {
            var precio_id = $(this).val();
            if(precio_id){
                $.ajax({
                    data:{'precio_id': precio_id},
                    url:"{% url 'pedido-ajax-precio' %}",
                    type:'GET',
                    success: function(data){
                        $('#id_costo_u').val(data[0]['precio']);
                        $('#id_color').val(data[0]['color']);
                        $('#id_anchocalamina').val(data[0]['materia__ancho']);
                        mdisponibles = data[0]['materia__stock'];
                        $('#informacionid').html('Metros Disponibles: '+mdisponibles);
                        precio = data[0]['precio'];
                        $.ajax({
                            data:{'id': data[0]['materia_id']},
                            url:"{% url 'material-ajax-material' %}",
                            type:'GET',
                            success: function(data1){
                                //alert(data1[0]['id']);
                                var ht = '<option value="'+data1[0]['id']+'" selected>'+ data1[0]['ancho']+'</option>';
                                //$('#id_anchocalamina option[value='+data1[0]['id']+']').attr('selected','selected');
                                $('#id_anchocalamina').html(ht);
                            },
                            failure: function(data1){
                                console.log('error')
                            }
                        });
                    },
                    failure: function(data){
                        console.log('error')
                    }
                });
            }else{
                $('#id_costo_u').val(0)
            }
        });
        $('#id_color').change(function () {
            var color = $(this).val();
            if(color){
                $.ajax({
                    data:{'color': color},
                    url:"{% url 'pedido-ajax-material' %}",
                    type:'GET',
                    success: function(data){
                        $('#id_ancho').html(data);
                    },
                    failure: function(data){
                        console.log('error')
                    }
                });
            }
        });
        $('#id_cantidad').keyup(function () {
            if($(this).val()){
                cantidad = $(this).val();
                tmetros = large * cantidad;
                var costo_t = tmetros * precio;
                var disponibles = mdisponibles - tmetros;
                $('#informacionid').html('Metros Disponibles: '+mdisponibles+' Metros Restantes: '+disponibles);
                $('#id_costo_t').val(costo_t);
                $('#id_total_m').val(tmetros);
            }
            else{
                cantidad = 0;
            }
        });
        $('#id_largo').keyup(function () {
            large = $('#id_largo').val();
            if(large!=null){
                tmetros = large * cantidad;
                var costo_t = tmetros * precio;
            $('#id_costo_t').val(costo_t);
                $('#id_total_m').val(large * cantidad);
            }else{
                tmetros = 0 * cantidad;
                var costo_t = tmetros * precio;
            $('#id_costo_t').val(costo_t);
                $('#id_total_m').val(0 * cantidad);
            }
        });
        $('#id_color').attr('readonly', 'readonly');
        $('#id_anchocalamina').attr('readonly', 'readonly');
    });
</script>
{% endblock %}

regalias/regalias/templates/ventas/calamina/new_detail_venta.html
{% extends 'base.html' %}

{% block title %}
Detalle Venta Calamina
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            {% include 'includes/__info_venta.html' %}
            <hr>
            <div class="col-md-3">
                <a href="{% url 'venta-pdf-detail' venta.id %}" class="btn btn-info" target="_blank">
                    <i class="fa fa-camera-retro"></i> Proforma
                </a>
            </div>
            <div class="col-md-3">
        <!--a href="{% url 'venta-new-add-material-calamina' venta.id %}" class="btn btn-success">
            <i class="fa fa-plus-circle"></i> Agregar Material
        </a-->
    </div>
    {% if detalles %}
    <div class="col-md-3">
        <a href="{% url 'venta-confirm' venta.id %}" class="btn btn-primary">
            <i class="fa fa-money-bill-alt"></i> Confirmar Venta
        </a>
    </div>
    {% endif %}
    <div class="col-md-3">
        <a href="{% url 'venta-delete' venta.id %}" class="btn btn-danger">
            <i class="fa fa-money-bill-alt"></i> Cancelar Venta
        </a>
    </div>
    
    <hr>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="app">Materiales Agregados <small style="font-family:arial">Lista de materiales</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table striped table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Codigo Calamina</th>
                            <th>Tipo Calamina</th>
                            <th>Color</th>
                            <th>Espesor(mm)</th>
                            <th>Ancho(ml)</th>
                            <th>Precio ml(Bs)</th>
                            <th>Tamaño(ml)</th>
                            <th>Cantidad</th>
                            <th>Costo Total(Bs)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for detalle in detalles %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ detalle.preciocalamina.codigo }}</td>
                            <td>{{ detalle.tipo }}</td>
                            <td>{{ detalle.preciocalamina.color }}</td>
                            <td>{{ detalle.preciocalamina.espesor }}</td>
                            <td>{{ detalle.preciocalamina.ancho }}</td>
                            <td>{{ detalle.precio_id }}</td>
                            <td>{{ detalle.largo }}</td>
                            <td>{{ detalle.cantidad }}</td>
                            <td>{{ detalle.costo_t }}</td>
                            <td>
                                <a href="{% url 'venta-delete-calamina' detalle.id %}" title="Eliminar Material", class="btn btn-danger">
                                    <i class="fa fa-close"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        <form action="{% url 'venta-new-add-material-calamina-new' venta.id %}" method="post">{% csrf_token %}
                            <tr>
                                <td></td>
                                <td>
                                    <div class="form-groups di">
                                        <input type="text" class="form-control" id="codigo_id" name="codigo_id">
                                    </div>
                                    <div class="hide">
                                        <input type="text" class="form-control" id="preciocalamina_id" name="preciocalamina_id">
                                    </div>
                                </td>
                                <td id="tipocalamina"></td>
                                <td id="colorcalamina"></td>
                                <td id="espesorcalamina"></td>
                                <td id="anchocalamina"></td>
                                <td id="preciocalamina"></td>
                                <td>
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="largo_id" required name="largo_id">
                                    </div>
                                </td>
                                <td>
                                    <div class="form-group">
                                        <input type="number" class="form-control" id="cantidad_id" required name="cantidad_id">
                                    </div>
                                </td>
                                <td id="preciototalcalamina"></td>
                                <td>
                                    <button type="submit" class="btn btn-info">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </td>
                            </tr>
                        </form>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
</div>
<style>
.form-control.tt-hint{
    display: none;
}
</style>
{% endblock %}

{% block js %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/examples.css' %}">
<script src="{% static 'js/typeahead.bundle.js' %}"></script>

<script>
var substringMatcher = function(strs) {
    return function findMatches(q, cb) {
        var matches, substringRegex;
        matches = [];
        substrRegex = new RegExp(q, 'i');
        $.each(strs, function(i, str) {
            if (substrRegex.test(str)) {
                matches.push(str);
            }
        });
        cb(matches);
    };
};
var states = [
{% for precio in precios %}
'{{ precio.codigo }}',
{% endfor %}
];

$('#codigo_id').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
},
{
    name: 'states',
    source: substringMatcher(states)
});
$(document).ready(function () {
    var largo = 0;
    var cantidad = 0;
    var total = 0;
    var precio = 0;
    $('#codigo_id').change(function () {
        var name = $(this).val();
        $.ajax({
            data:{'name': name},
            url:"{% url 'pedido-ajax-precio-calamina' %}",
            type:'GET',
            success: function(data){
                if(data){
                    $('#tipocalamina').html(data[0]['tipo__tipo']);
                    $('#preciocalamina').html(data[0]['precio']);
                    $('#espesorcalamina').html(data[0]['espesor']);
                    $('#anchocalamina').html(data[0]['ancho']);
                    $('#colorcalamina').html(data[0]['color__color']);
                    precio = data[0]['precio'];
                    $('#preciocalamina_id').val(data[0]['id']);
                }
                else{
                    $('#id_direccion').val(null);
                    $('#id_representante').val(null);
                    $('#id_telefono').val(null);
                    $('#id_email').val(null);
                    $('#id_nit').val(null);
                }
            },
            failure: function(data){
                console.log('error')
            }
        });
    });
    $('#largo_id').keyup(function () {
        largo = $('#largo_id').val();
        if(cantidad > 0){
            total = cantidad * largo;
            $('#preciototalcalamina').html(total * precio);
        }
    });
    $('#cantidad_id').keyup(function () {
        cantidad = $('#cantidad_id').val();
        if(largo > 0){
            total = cantidad * largo;
            $('#preciototalcalamina').html(total * precio);
        }
    });
});
</script>
{% endblock %}